name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build
    uses: soat-tech-challenge/github-workflows/.github/workflows/maven-bump-push-dockerhub.yml@main
    secrets: inherit
    with:
      docker: false